name: Docker Publish

concurrency:
  group: docker
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      dockerfile:
        description: 'The dockerfile to use'
        type: string
        required: true
        default: './Dockerfile'
      context:
        description: 'The context to use'
        type: string
        required: true
        default: '.'
      build-args:
        description: 'The build args to use'
        type: string
        required: false
        default: ''
      tags:
        description: 'The tags to use'
        type: string
        required: false
        default: ''
    secrets:
      DOCKERHUB_USERNAME:
        description: 'The username to use for the image'
        required: true
      DOCKERHUB_TOKEN:
        description: 'The password to use for the image'
        required: true

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ${{ inputs.dockerfile }}
          tags: ${{ inputs.tags }}
          build-args: ${{ inputs.build-args }}
